{"id":"../../node_modules/axios/lib/cancel/CanceledError.js","dependencies":[{"name":"D:\\learning-projects\\js\\natours\\package.json","includedInParent":true,"mtime":1738789525091},{"name":"D:\\learning-projects\\js\\natours\\node_modules\\axios\\package.json","includedInParent":true,"mtime":1737806351315},{"name":"../core/AxiosError.js","loc":{"line":3,"column":23,"index":38},"parent":"D:\\learning-projects\\js\\natours\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"D:\\learning-projects\\js\\natours\\node_modules\\axios\\lib\\core\\AxiosError.js"},{"name":"../utils.js","loc":{"line":4,"column":18,"index":81},"parent":"D:\\learning-projects\\js\\natours\\node_modules\\axios\\lib\\cancel\\CanceledError.js","resolved":"D:\\learning-projects\\js\\natours\\node_modules\\axios\\lib\\utils.js"}],"generated":{"js":"'use strict';\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = void 0;\nvar _AxiosError = _interopRequireDefault(require(\"../core/AxiosError.js\"));\nvar _utils = _interopRequireDefault(require(\"../utils.js\"));\nfunction _interopRequireDefault(e) { return e && e.__esModule ? e : { default: e }; }\n/**\n * A `CanceledError` is an object that is thrown when an operation is canceled.\n *\n * @param {string=} message The message.\n * @param {Object=} config The config.\n * @param {Object=} request The request.\n *\n * @returns {CanceledError} The created error.\n */\nfunction CanceledError(message, config, request) {\n  // eslint-disable-next-line no-eq-null,eqeqeq\n  _AxiosError.default.call(this, message == null ? 'canceled' : message, _AxiosError.default.ERR_CANCELED, config, request);\n  this.name = 'CanceledError';\n}\n_utils.default.inherits(CanceledError, _AxiosError.default, {\n  __CANCEL__: true\n});\nvar _default = exports.default = CanceledError;"},"sourceMaps":null,"error":null,"hash":"acd1cd012c13d336d69fbf2014e64b83","cacheData":{"env":{}}}